apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gcr.io/striped-weaver-161318/hello-k8s-app
#        livenessProbe:
#          httpGet:
#            path: /health
#            port: 5000
        ports:
          - containerPort: 8080
#        resources:
#          limits:
#            cpu: 300m
#            memory: 480Mi
