apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: gcr.io/striped-weaver-161318/hello-docker-ecs
        #image: hello-docker-ecs:latest
        livenessProbe:
          httpGet:
            path: /
            port: 5000
        ports:
          - containerPort: 5000
        resources:
          limits:
            cpu: 300m
            memory: 480Mi
